# Generated by Django 5.1.7 on 2025-03-29 14:15

import pokemon_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='type',
            field=models.CharField(default='normal', validators=[pokemon_app.validators.validate_type]),
        ),
    ]
